name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.11.1
        include:
          - os: ubuntu-latest
            ocaml-version: 4.07.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam pin add . -y --no-action
      - run: opam depext -y toml toml_cconv
      - run: opam install -y ./*.opam --deps-only --with-test
      - run: opam upgrade --fixup
      - run: opam exec -- dune build @install
      - run: opam exec -- dune runtest
